### ISSUE TITLE
Is it possible to use OpenGL backend on Windows?

### ISSUE THREAD

**Issue by YDS67** [floooh/sokol-rust#20]
First, let me say, it's a pretty cool library, and great bindings. But I have some questions.

Is there a way to pick OpenGL backend when compiling on/for Windows? I'd rather not bother with multiple backends, I'm developing on Linux, and only interested in Windows/Linux desktop application.

I also prefer writing glsl shaders by hand rather than using extra tools to convert between different formats. Converting shader code to byte array is easy, but writing hlsl shaders is a pain, and I couldn't make shdc work so far (and I prefer not using anything except cargo to be honest).

I've edited the texturecube example a little [here](https://github.com/YDS67/sokol-rs-simple-example) to show what I want (kept D3d11 backend for now to compile on Windows). Made a little utility to translate shader code to byte arrays. Included an input loop. So far this library is exactly what I want, except for the hlsl shaders on Windows.

**Comment by floooh** [comment]
Looking at the build.rs file it looks like the backend is configurable from the outside via environment variables (not sure if this is the "best practice" to configure Rust projects though:

https://github.com/floooh/sokol-rust/blob/c445b2bb930be6885093242eb563b069460157f5/build.rs#L33

...e.g. setting an environment variable `SOKOL_BACKEND=GL" before building should do the job (the actual compiler definition is then selected here: https://github.com/floooh/sokol-rust/blob/c445b2bb930be6885093242eb563b069460157f5/build.rs#L72-L118

**Comment by floooh** [comment]
Regarding sokol-shdc, in the Zig build file I have added a build step like this, but this is just a helper to recompile the shader files, it's not as fancy as the cmake integration I use in the sokol-samples (where the shader compiler is integrated fully into the regular build process).

https://github.com/floooh/sokol-zig/blob/24134d507a9b6d61ea1c438c0ec2ffd19530a93c/build.zig#L212-L254

**Comment by YDS67** [comment]
Setting the global variable (in global Cargo config file on Windows) worked like a charm. Thank you!
I know I'm missing out on many features, but I'd rather stick to something I know for now.

**Comment by YDS67** [comment]
Sorry, forgot, closing the issue now
