### ISSUE TITLE
New warning: creating a mutable reference to mutable static is discouraged

### ISSUE THREAD

**Issue by waywardmonkeys** [floooh/sokol-rust#26]
```
warning: creating a mutable reference to mutable static is discouraged
   --> examples/cube/cube.rs:114:26
    |
114 |     let state = unsafe { &mut STATE };
    |                          ^^^^^^^^^^ mutable reference to mutable static
    |
    = note: for more information, see issue #114447 <https://github.com/rust-lang/rust/issues/114447>
    = note: this will be a hard error in the 2024 edition
    = note: this mutable reference has lifetime `'static`, but if the static gets accessed (read or written) by any other means, or any other reference is created, then any further use of this mutable reference is Undefined Behavior
help: use `addr_of_mut!` instead to create a raw pointer
    |
114 |     let state = unsafe { addr_of_mut!(STATE) };
    |                          ~~~~~~~~~~~~~~~~~~~
```

**Comment by floooh** [comment]
Yeah I noticed that too when testing with Rust 1.77, but just pushed the investigation to the side for now until I see the end of the tunnel in my current sokol-shdc work :)

**Comment by waywardmonkeys** [comment]
Just filing it for future reference ...

**Comment by floooh** [comment]
Ooof, I tinkered around a bit following Rust's error hints and the result looks even worse (Rust really doesn't like global mutable state it seems).

**Comment by floooh** [comment]
Wild idea: sokol-app has alternative userdata callbacks. It might be possible to come up with a Rust wrapper which passes a state reference from the sapp::run() function into the callbacks similar to what https://github.com/rust-windowing/winit does:

```rust
    let mut app = ControlFlowDemo::default();
    event_loop.run_app(&mut app)
```

**Comment by gw3583** [comment]
Added one possible workaround for this in https://github.com/floooh/sokol-rust/pull/30 - makes use of the user_data support to pass a heap allocated state struct.

**Comment by floooh** [comment]
https://github.com/floooh/sokol-rust/pull/30 merged.
